### ISSUE TITLE
发现一处错误

### ISSUE THREAD

**Issue by sakiyo** [easy-swoole/redis#21]
此文件
EasySwoole\Redis\Config\RedisConfig ;
定义常量值重复
public const SERIALIZE_NONE = 0;
public const SERIALIZE_PHP = 1;
public const SERIALIZE_JSON = 1;

SERIALIZE_JSON 应该是2
目前直接使用的时候如果选用SERIALIZE_JSON ，实际执行的是SERIALIZE_PHP 所对应的序列化与反序列化方法。

**Comment by tioncico** [comment]
好的,多谢反馈,之前没注意到,已修正
