### ISSUE TITLE
反序列化不严谨，如果存入的数据是空（空数组，空值），返回的确实序列化的字符串

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/redis#33]
https://github.com/easy-swoole/redis/blob/1f245efc30871fbc5ec8e6e80ad456c56bdaf803/src/CommandHandel/AbstractCommandHandel.php#L117

比如传入的数据是 `array()`，读取的数据应该是 `array()`，而这个方法返回的却是 `a:0:{}`。

**Comment by tioncico** [comment]
好的,尽快修复

**Comment by tioncico** [comment]
https://github.com/easy-swoole/redis/pull/34
