### ISSUE TITLE
关于有序集合zScore获取数字类型成员分数值得问题

### ISSUE THREAD

**Issue by ylyd** [easy-swoole/redis#43]
我的代码：$uid是整数类型
`$fd = $redis->zScore($key, $uid);`
PHP运行得到结果null；在redis-cli中可以得到正确结果

PHP运行截图：
![微信截图_20200406143639](https://user-images.githubusercontent.com/43955181/78530122-a79dbb80-7815-11ea-96d9-245a766babef.png)

redis-cli中运行结果截图：
![微信截图_20200406143327](https://user-images.githubusercontent.com/43955181/78530038-850ba280-7815-11ea-9f00-271390fe3f36.png)

**Comment by tioncico** [comment]
刚刚测试,
redis-cli新增数据:
```
zadd testa 1 1
```
php调用redis组件获取
```php
        $redisConfig = new \EasySwoole\Redis\Config\RedisConfig();
        $redis = new \EasySwoole\Redis\Redis($redisConfig);
        $fd = $redis->zScore('testa', 1);
        var_dump($fd);
```
输出正常
