### ISSUE TITLE
lPush批量添加报错

### ISSUE THREAD

**Issue by hsk-story** [easy-swoole/redis#46]
报错代码在45行
https://github.com/easy-swoole/redis/blob/master/src/Client.php#L40-L50

当lPush第二个参数传入数组时, 也就是批量push进list时, 报错
`strlen() expects parameter 1 to be string, array given`

看样子是没有对lPush的实现层没有写好批量push的功能

**Comment by tioncico** [comment]
include "../vendor/autoload.php";
go(function () {
    $redis = new \EasySwoole\Redis\Redis(new \EasySwoole\Redis\Config\RedisConfig([
    ]));

    $redis->lPush('b', 2,3,4,5);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
});

**Comment by tioncico** [comment]
```
include "../vendor/autoload.php";
go(function () {
    $redis = new \EasySwoole\Redis\Redis(new \EasySwoole\Redis\Config\RedisConfig([
    ]));

    $redis->lPush('b', 2,3,4,5);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
    $data = $redis->lpop('b');
    var_dump($data);
});
```

**Comment by hsk-story** [comment]
是我这边调用方式弄错了
